### ISSUE TITLE
Resource Already Registered Error 

### ISSUE THREAD

**Issue by sushantshirekar** [AmazonAppDev/amazon-iap-kotlin#2]
Hello Amazon Support Team,

I’m reaching out regarding our latest app submission, which was rejected due to a recurring crash issue in the Live App Testing (LAT) environment. This is the same issue that we raised in previous cases (ID 16543450591 and 16385671891), for which we have not yet received any guidance or resolution.

The error we’re encountering is as follows:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.travelxp.firetv/com.travelxp.firetv.MainActivity}: com.amazon.a.a.o.a.b: Resource already registered: I4.e@609ffea
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2953)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3094)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:6775)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: com.amazon.a.a.o.a.b: Resource already registered: I4.e@609ffea
at w2.b.a(SourceFile:89)
at n2.a.<init>(SourceFile:189)
at n2.a.b(SourceFile:24)
at com.travelxp.firetv.MainActivity.onCreate(SourceFile:51)
at android.app.Activity.performCreate(Activity.java:7169)
at android.app.Activity.performCreate(Activity.java:7159)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3094)
...

This issue has prevented us from pushing critical updates live, causing significant delays. Could you please urgently escalate this to the engineering team and advise us on next steps? We need to understand if a direct deployment to the live environment could bypass this crash or if there are specific troubleshooting steps we can take to resolve the LAT crash.

Thank you for your immediate attention to this matter, as it’s crucial to ensure our app update reaches users without further delay.

Best regards,
Sushant

**Comment by giolaq** [comment]
Hi @sushantshirekar , you can use the [ forum ](https://community.amazondeveloper.com/) to signal your issue related to LAT.  This issue section is only about the specific demo code. Thank you
